
volumes:
  static:
  postgresdata:
  dump-db:
  redisdata:
  esdata:

  
services:

  db:
    container_name: postgres
    image: postgres:13.4
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data/
      - ./movies_admin/create_schem.sql:/docker-entrypoint-initdb.d/create_schem.sql
    ports:
      - "5432:5432"
    env_file:
      - ./.dev.env

  admin_panel:
    container_name: admin_panel
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env

  nginx:
    image: nginx:1.21.1
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/code/static/
    ports:
      - "80:80"
    depends_on:
      - admin_panel

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
        
  redis:
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    image: redis:6.2.5
    volumes:
      - redisdata:/data

  etl:
    container_name: etl
    build:
      context: ./etl_es
      dockerfile: Dockerfile
    env_file:
      - ./.dev.env
    volumes:
      - ./etl_es:/etl
    depends_on:
      - es
      - redis
      - admin_panel