-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS content;


CREATE TABLE IF NOT EXISTS content.genre
(
    id uuid NOT NULL,
    name varchar(512)[] NOT NULL,
    description text,
    created timestamp with time zone,
    modified timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS content.genre_film_work
(
    id uuid NOT NULL,
    genre_id uuid NOT NULL,
    film_work_id uuid NOT NULL,
    created timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS content.film_work
(
    id uuid NOT NULL,
    title varchar(512)[] NOT NULL,
    description text,
    creation_date timestamp with time zone,
    rating real,
    type varchar(10)[],
    created timestamp without time zone,
    modified timestamp without time zone[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS content.person_film_work
(
    id uuid NOT NULL,
    person_id uuid NOT NULL,
    film_work_id uuid NOT NULL,
    role text,
    created timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS content.person
(
    id uuid NOT NULL,
    full_name text NOT NULL,
    birth_date date,
    created timestamp with time zone,
    modified timestamp with time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS content.genre_film_work
    ADD CONSTRAINT fk_genre_film FOREIGN KEY (genre_id)
    REFERENCES content.genre (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS content.genre_film_work
    ADD CONSTRAINT fk_film_work_genre FOREIGN KEY (film_work_id)
    REFERENCES content.film_work (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS content.person_film_work
    ADD CONSTRAINT fk_person_film FOREIGN KEY (person_id)
    REFERENCES content.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS content.person_film_work
    ADD CONSTRAINT fk_film_person FOREIGN KEY (film_work_id)
    REFERENCES content.film_work (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

CREATE UNIQUE INDEX IF NOT EXISTS film_work_genre_idx
    ON content.genre_film_work USING btree
    (film_work_id ASC NULLS LAST, genre_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS film_work_person_idx
    ON content.person_film_work USING btree
    (film_work_id ASC NULLS LAST, person_id ASC NULLS LAST, role COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

END;